AllCops:
  TargetRubyVersion: 3.2.2
  NewCops: enable
  Exclude:
    - bin/*
    - vendor/bundle/**/*

Naming/ClassAndModuleCamelCase:
  Exclude:
    - 'config/initializers/**/*.rb'

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*.rb'

Metrics/MethodLength:
  Max: 30
  Exclude:
    - 'spec/**/*'

Style/Documentation:
  Exclude:
    - 'app/**/*.rb'
    - 'config/**/*.rb'