AllCops:
  TargetRubyVersion: 3.2.2
  NewCops: enable
  Include:
    - spec/**/*.rb
  Exclude:
    - bin/bundle
    - bin/setup


Metrics/BlockLength:
  Exclude:
    - 'spec/**/*.rb'

Metrics/MethodLength:
  Max: 30
  Exclude:
    - 'spec/**/*'
