version: '3'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  redis_test:
    image: redis:latest
    command: redis-server --port 6380
    ports:
      - "6380:6380"

  app:
    build:
      context: .
    depends_on:
      - db
      - redis_test
    environment:
      RAILS_ENV: test
      REDIS_TEST_URL: redis://redis_test:6380

volumes:
  postgres_data: