# setup the database
databases:
  - name: rails_scraper
    databaseName: rails_scraper
    user: rails_scraper_user

services:
  # redis for cache
  - type: redis
    name: redis
    ipAllowList: [] # only allow internal connections
    plan: free # optional (defaults to starter)
    maxmemoryPolicy: allkeys-lru

  #  main app
  - type: web
    name: rails_scraper
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: rails_scraper
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
      - key: REDIS_URL # this must match the name of the environment variable used in production.rb
        fromService:
          type: redis
          name: redis
          property: connectionString
