production:
  proxy_key: 'your-key'
  redis_url: 'redis-url'

development:
  proxy_key: 'your-key'
  redis_url: 'redis://localhost:6379'

test:
  proxy_key: 'your-key'
  redis_url: 'redis://localhost:6379'
