default: &default
  adapter: postgresql
  encoding: unicode
  pool: 25
  timeout: 5000
  url: postgres://postgres:postgres@127.0.0.1

development:
  <<: *default
  database: rails_scraper_development

test:
  <<: *default
  database: rails_scraper_test

production:
  <<: *default
  database: rails_scraper_production
