name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    env:
      RAILS_ENV: test
      REDIS_TEST_URL: redis://localhost:6380
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2.2
          bundler-cache: true

      - name: Build and Test
        run: |
          docker-compose -f docker-compose.yml build
          docker-compose -f docker-compose.yml run --rm app bundle install
          docker-compose -f docker-compose.yml run --rm app bin/rails db:create db:migrate
          docker-compose -f docker-compose.yml run --rm app bin/rails test

